### ISSUE TITLE
attn_combine is defined but not used in BahdanauDecoder forward process

### ISSUE THREAD

**Issue by RHzhongzju** [gabrielloye/Attention_Seq2seq-Translation#2]
Hello, Gabriel!
Thanks for your article on the Attention Mechanism!
In the article, you provided the equation to calculate the alignment scores for Bahdanau Attention, but in the code, the attn_combine was defined but not used in the forward process.

**Comment by gabrielloye** [comment]
Hi @RHzhongzju,
Thanks for pointing that out! Yes, defining attn_combine was unnecessary as it isn't used in the calculation of alignment scores and I've since removed it from the notebook.
